server:
  port: 9996

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/restaurant
    name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


kafka:
  server: localhost:29092
  offset-reset: latest
  topics:
    bill: bill.topic
  groupId:
    bill: group.bill.topic

project:
  path:
    bill: bills/