server:
  port: 9999

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/restaurant
    name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update


kafka:
  server: localhost:29092
  offset-reset: latest
  topics:
    new: new.topic
    cook: cook.topic
    bill: bill.topic
  groupId:
    cook: group.cook.topic
